name: appcore
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_esc_pos_utils: ^1.0.1
  intl: ^0.20.2
  responsive_framework: ^1.5.1
  flutter_staggered_animations: ^1.1.1
  isar: ^3.1.0+1
  flutter_svg: ^2.0.9
  go_router: ^14.8.1
  # go_router: ^14.6.0
  back_button_interceptor: ^8.0.4
  either_dart: ^1.0.0
  toastification: ^2.3.0
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  http: ^1.2.2
  # easy_localization: ^3.0.7
  flutter_animate: ^4.5.0
  custom_refresh_indicator: ^4.0.1
  expandable_page_view: ^1.0.17
  smooth_page_indicator: ^1.2.0+3
  pinput: ^5.0.0
  dropdown_button2: ^2.3.9
  fl_chart: ^0.69.1
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  calendar_date_picker2: ^1.1.7
  flutter_staggered_grid_view: ^0.7.0
  container_tab_indicator: ^0.3.0
  pretty_qr_code: ^3.3.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
